config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  
  resources :events do
    resources :rsvps
    resources :likes
  end
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :rsvps, -> { includes(:user) }
  has_many :likes, -> { includes(:user) }

  default_scope { order('start_time') } 

  attr_accessor :start_date_date, :start_date_time, :end_date_date, :end_date_time
 
  after_initialize :get_datetimes
  before_validation :set_datetimes

  DATE_FORMAT = "%d %B, %Y"
  TIME_FORMAT = "%I:%M%p"
  DATE_AND_TIME_FORMAT = DATE_FORMAT + " " + TIME_FORMAT
  DATE_AND_TIME_FORMAT_SHORT = "%a, %b %d at %I:%M%p"

  def start_time_display
    format_display_date(self.start_time)
  end

  def end_time_display
    format_display_date(self.end_time)
  end

  def start_time_display_short
    format_display_date_short(self.start_time)
  end

  def end_time_display_short
    format_display_date_short(self.end_time)
  end

  def can_modify(user)
    (user && ( (user.id == self.user_id) || user.is_admin) )
  end

  def num_rsvps
    rsvps.length
  end

  private

    def format_display_date(date)
      date.strftime(DATE_AND_TIME_FORMAT)
    end

    def format_display_date_short(date)
      date.strftime(DATE_AND_TIME_FORMAT_SHORT)
    end

    def get_datetimes
      if (self.start_time)
        self.start_date_date = self.start_time.strftime(DATE_FORMAT)
        self.start_date_time = self.start_time.strftime(TIME_FORMAT)
      end
      if (self.end_time)
        self.end_date_date   = self.end_time.strftime(DATE_FORMAT)
        self.end_date_time   = self.end_time.strftime(TIME_FORMAT)
      end
    end

    def set_datetimes
      if (self.start_date_date && self.start_date_time)
        date_str = self.start_date_date + self.start_date_time
        Rails.logger.debug("date_str = #{date_str}")
        new_date = DateTime.parse(date_str)
        Rails.logger.debug("new date = #{new_date}")
        self.start_time = new_date
      end

      if (self.end_date_date && self.end_date_time)
        date_str = self.end_date_date + self.end_date_time
        Rails.logger.debug("date_str = #{date_str}")
        new_date = DateTime.parse(date_str)
        Rails.logger.debug("new date = #{new_date}")
        self.end_time = new_date
      end
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :init_rsvps, only: [:show]

  # GET /events
  # GET /events.json
  def index
    @events = Event.where('start_time > ?', DateTime.now).all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def init_rsvps
      if current_user
        @rsvp_id_arr = @event.rsvps.map { |rsvp| rsvp.user.id }
        @current_user_already_rsvp = @rsvp_id_arr.include? current_user.id
        @current_user_rsvp_id = @current_user_already_rsvp ? current_user.rsvp_id_for_event(@event) : nil 
        @liked_user_id_arr = current_user.liked_user_id_arr_by_event(@event)
        #below is a hash of liked_users to the like_id in order to set unlike button
        @curr_user_liked_user_to_liked_id_hash = 
          current_user.likes.where(event_id: @event.id).inject({}) { |r,c| r.merge c.liked_user_id => c.id }
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:user_id, :title, :venue_name, :venue_address, :venue_zip, :description, :start_time, :end_time, :start_date_date, :start_date_time, :end_date_date, :end_date_time)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_rsvp_list.html.erb
<div class="center-align">

  <% if @current_user_rsvp_id  %>
     <button class="btn waves-effect waves-light orange event-unrsvp" data-event-id="<%= event.id %>" data-rsvp-id="<%= @current_user_rsvp_id %>">UnRsvp</button>
  <% elsif current_user %>
    <button class="btn waves-effect waves-light orange event-rsvp" data-event-id="<%=event.id %>">RSVP to event</button>
  <% else %>
    <button class="btn waves-effect waves-light orange disabled">Login to Rsvp</button>
  <% end %>

  <% if @current_user_rsvp_id %>
    <%= link_to 'My matches', event_likes_path(@event), class: "btn waves-effect waves-light orange" %>
  <% else %>
    <button class="btn waves-effect waves-light orange disabled">Rsvp for matches</button>
  <% end %>
</div>

<% event.rsvps.each do |rsvp| %>
  <% unless current_user && (rsvp.user_id == current_user.id) %>
    <% cardColor = (rsvp.user.gender == 'Male' ? 'blue lighten-2' : (rsvp.user.gender == 'Female' ? 'pink lighten-2' : 'blue-grey lighten-2')) %>
    <div class="row">
      <div class="col s12">
        <div class="card <%= cardColor %>">
          <div class="card-content white-text">
            <span class="card-title"><%= avatar_url(rsvp.user, { size: :thumb, class: "circle", alt: "" }) %> <%= rsvp.user.display_name %> (Code: <%= rsvp.code %>)</span>
            <!--
                <span class="card-title"> <%= image_tag rsvp.user.avatar.url(:thumb), alt: "", class: "circle" %> <%= rsvp.user.display_name %> (Code: <%= rsvp.code %>)</span>
              -->
          </div>
          <% if current_user && current_user_already_rsvp %>
            <div class="card-action">
              <% if @liked_user_id_arr.include?(rsvp.user_id) %>
                <% if like_id = @curr_user_liked_user_to_liked_id_hash[rsvp.user_id] %> 
                  <button class="btn waves-effect waves-light orange event-toggle-like-user user-likes"  data-action="UnLike" data-event-id="<%= event.id %>" data-like-id="<%= like_id %>" data-liked-user-id="<%= rsvp.user_id %>"><i class="material-icons left">thumb_down</i> Unlike</button>
                <% else %>
                 <!-- Could not get like_id for user -->
                <% end %>
              <% else %>
                  <button class="btn waves-effect waves-light orange event-toggle-like-user" data-event-id="<%= event.id %>" data-action="Like" data-liked-user-id="<%= rsvp.user_id %>"><i class="material-icons left">thumb_up</i> Like</button>
              <% end %>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :venue_name %>
    <%= f.text_field :venue_name %>
  </div>

  <div class="field">
    <%= f.label :venue_address %>
    <%= f.text_field :venue_address %>
  </div>

  <div class="field">
    <%= f.label :venue_zip %>
    <%= f.text_field :venue_zip %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :start_date_date, "Start Date" %>
    <%= f.text_field :start_date_date, class: "datepicker"%>
  </div>

  <div class="field">
    <%= f.label :start_date_time, 'Start Time' %>
    <%= f.text_field :start_date_time, class: "timepicker"%>
  </div>

  <div class="field">
    <%= f.label :end_date_date, "End Date" %>
    <%= f.text_field :end_date_date, class: "datepicker"%>
  </div>

  <div class="field">
    <%= f.label :end_date_time, 'End Time' %>
    <%= f.text_field :end_date_time, class: "timepicker"%>
  </div>

 

  <div class="actions">
    <%= f.submit class: "btn waves-effect waves-light orange" %>
  </div>
<% end %>
<script type="text/javascript">
    $('#event_start_date_time').clockpicker({
      placement: 'bottom',
      align: 'left',
      twelvehour: true
    });
    $('#event_end_date_time').clockpicker({
      placement: 'bottom',
      align: 'left',
      twelvehour: true
    });
    $('.input_endtime').clockpicker({
      placement: 'bottom',
      align: 'left',
      darktheme: true,
      twelvehour: false
    });
    $('.datepicker').pickadate();
  </script>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h2 class="center-align">Events</h2>

<% @events.each do |event| %>
  <div class="row">
    <div class="col s12">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title white-text"><%= event.title %>  <span class="badge red" data-badge-caption="Rsvps"><%= event.num_rsvps %></span></span>
          <p>Time: <%= event.start_time_display_short %> <% if event.end_time %> to <%= event.end_time_display_short %> <% end %>
          </p>
          <br >

          <p>Venue: <%= event.venue_name %><br />
            <%= event.venue_address %> <%= event.venue_zip %>
          </p>
          
        <div>
        <div class="card-action">
          <%= link_to 'Show Event', event, class: "btn waves-effect waves-light orange" %>
          <% if (event.can_modify(current_user)) %>
            <%= link_to 'Edit', edit_event_path(event), class: "btn waves-effect waves-light orange" %>
            <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn waves-effect waves-light orange" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= link_to 'New Event', new_event_path, class: "btn waves-effect waves-light orange" %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="row">
  <div class="col s10  offset-s1">
    <h3 class="center-align"><%= @event.title %></h3>
    <div class="center-align">
      <%= link_to events_path, class: "btn waves-effect waves-light"  do %>
        <i class="material-icons left">assignment_return</i> Back
      <% end %>
     
    </div>
    <% if current_user && @event.can_modify(current_user) %>
      <div class="center-align"><%= link_to 'Edit', edit_event_path(@event), class: "btn waves-effect waves-light orange" %> </div>
    <% end %>

    <div class="card-panel">

      <div class="venue">
        <strong>Where:</strong><br />
        <%= @event.venue_name %><br />
        <%= @event.venue_address %> <%= @event.venue_zip %>
      </div>

    </div>
    <div class="card-panel">
      <div class="event-time">
        <strong>When:</strong><br />
        <%= @event.start_time_display_short %> - <%= @event.end_time_display_short %>
      </div>
    </div>

    <div class="card-panel">
      <strong>Event Info:</strong>

      <div class="event-description">
          <%= @event.description %>
      </div>

    </div>

<hr />
<h3 class="center-align">RSVPs</h3>


<div id="event_rsvp_list" >
  <%= render partial: 'event_rsvp_list', locals: {event: @event, current_user_already_rsvp: @current_user_already_rsvp }  %>
</div>